controller_list:
  - name: fake_irb_120_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
initial:  # Define initial robot poses per group
  - group: irb_120_robot
    pose: rest_pose